### PR TITLE
applied b64 enc/dec fix

### PR DESCRIPTION
**Pull request by freakeinstein**
Fix for the issue - https://github.com/a-mma/AquilaDB/issues/26

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
Surprising to me that the test is failing. For my use-case, the fix is working perfectly (and I only made the change in src/core/faissclient/index.js -- since I'm using the Python API wrapper).

**Comment by jeremybmerrill** [comment]
thanks!

**Comment by freakeinstein** [comment]
@jeremybmerrill Please note that the changes are now available in develop branch only, which means you need to pull docker image with label `bleeding` from Docker hub.

**Comment by jeremybmerrill** [comment]
@freakeinstein Thanks!

**Pull request merged**
