### PR TITLE
search_k parameter for annoy

### PR DESCRIPTION
**Pull request by sopaoglu**
search_k parameter is added for annoy, it is one of the parameters to tune Annoy

### CODE REVIEW

**Comment by sopaoglu** [comment]
Actually, I don't understand what is wrong, it shows an error when it runs test.js. However, it is running on my machine

**Comment by freakeinstein** [comment]
@sopaoglu Hmm.. I'm also confused. Don't seen an issue in code. Let's keep this pull request open and try finding the reason meanwhile. I like this change anyway!

**Comment by freakeinstein** [comment]
Ha.. I missed that colon too.. 😅

**Comment by sopaoglu** [comment]
🙈,
Have a nice day

jubin jose <notifications@github.com> şunları yazdı (9 Oca 2020 07:19):

**Comment by freakeinstein** [comment]
Have an awesome day! spread the word too.. 🤪

**Pull request merged**
